@startuml
() main

class ImportPicture {
	params : AppParameters
	imgFolder : ImgFolder
	gpxFolder : GpxFolder
	void main()
	void setUp()
	void run()
}

class AppParameters
class ImgFolder<ImgFile><<ArrayList>> {
	void procGPXfile()
}
class ImgFile<<File>> {
	getDate() : Date
	+ procImageFile(,,,)
	+ exportToFile(,,)
	- exifWrite()
	printinfo()
}

class GpxFolder<GpxFile><<ArrayList>> {
	params : AppParameters
	GpxFile
	printinfo()
}
class GpxFile<<File>> {
	gpx : GpxParser
	parse()
	printinfo()
}
class GpxParser<<DefaultHandler>> {
	tag : TagTrkpt
	trkpt : ElementMapTRKPT
	trkseg : ElementMapTRKSEG
}
class ElementMapTRKPT<Date,TagTrkpt><<TreeMap>> {
	getValue(Date) : TagTrkpt
	printinfo()
}
class ElementMapTRKSEG<Date,ElementMapTRKPT><<TreeMap>> {
	printheader()
	printfooter()
	printinfo()
}
class TagTrkpt<<Cloneable>> {
	lat : Double
	lon : Double
	eleStr : String
	time : Date
	magvarStr : String
	speedStr : String
}

main -> ImportPicture : 1:setUp >

AppParameters <--o ImportPicture : 1.1:new\n1.2:printout <
ImportPicture o--> ImgFolder : 1.3:new\n2.3:procGPXfile(gpx,date)\n2.4:printinfo() >
ImportPicture o--> GpxFolder : 1.4:new\n2.2:printinfo() >
ImportPicture --> ImportPicture : 2:start >

GpxFolder *--> GpxFile : 1.4.1:new\n1.4.2:parse() >
GpxFile *-> GpxParser : 1.4.1.1:new
GpxParser o--> ElementMapTRKPT : 1.4.1.1.2:new(AppParameters)
GpxParser o--> ElementMapTRKSEG : 1.4.1.1.1:new
ElementMapTRKSEG o.. ElementMapTRKPT
ElementMapTRKPT *-- TagTrkpt

ImgFolder *--> ImgFile : 1.3.1:new\n2.3.1:procImageFile()\n2.3.2:exportToFile()\n2.4.1:printinfo() >
ImgFile ..> ElementMapTRKPT : 2.3.1.1:getValue(Date) >

@enduml

